trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'novya-serviceconnection'
  appName: 'backend-n'

steps:
  # Step 1: Only create requirements.txt - nothing else!
  - script: |
      echo "Setting up for Azure Oryx build..."
      
      # Create requirements.txt in root - this triggers Azure build
      cat > requirements.txt << 'EOF'
      fastapi==0.104.1
      uvicorn[standard]==0.24.0
      python-multipart==0.0.6
      openai==1.3.0
      python-dotenv==1.0.0
      anyio==3.7.1
      typing-extensions==4.8.0
      EOF
      
      echo "requirements.txt created for Azure build"
    displayName: 'Create requirements.txt'

  # Step 2: Deploy SOURCE CODE (not zip) - this is crucial!
  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      package: '$(System.DefaultWorkingDirectory)'