# azure-pipelines-fixed.yml
trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'novya-serviceconnection'
  appName: 'backend-n'
  pythonVersion: '3.11'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  - script: |
      echo "Installing dependencies..."
      pip install -r ai_backend/requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo "Testing application..."
      cd ai_backend
      python -c "from app import app; print('✅ App imports successfully')"
    displayName: 'Test app import'

  # Create requirements.txt in root for Oryx detection
  - script: |
      echo "Copying requirements.txt to root for Oryx..."
      cp ai_backend/requirements.txt requirements.txt
      echo "Requirements.txt content:"
      cat requirements.txt
    displayName: 'Setup for Oryx build'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      package: '$(Build.ArtifactStagingDirectory)/backend.zip'

  # Set startup command that installs dependencies first
  - task: AzureAppServiceManage@0
    displayName: 'Set Startup Command'
    inputs:
      azureSubscription: $(azureSubscription)
      Action: 'Start Azure App Service'
      WebAppName: $(appName)
      StartupCommand: 'python -m pip install -r requirements.txt && uvicorn ai_backend.app:app --host 0.0.0.0 --port 8000 --workers 2'