trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'novya-serviceconnection'
  appName: 'backend-n'

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Create proper requirements.txt in root (Azure looks for this)
  - script: |
      echo "Creating requirements.txt for Azure Oryx build..."
      
      # Create requirements.txt that Azure will use to build the app
      cat > requirements.txt << 'EOF'
      fastapi==0.104.1
      uvicorn[standard]==0.24.0
      python-multipart==0.0.6
      anyio==4.2.0
      typing-extensions==4.8.0
      pydantic==2.5.0
      python-dotenv==1.0.0
      openai==1.3.0
      EOF
      
      # Add any other requirements from ai_backend
      if [ -f "ai_backend/requirements.txt" ]; then
        echo "" >> requirements.txt
        # Filter out duplicates
        grep -v -E "^(fastapi|uvicorn|python-multipart|anyio|typing-extensions|pydantic|python-dotenv|openai)" ai_backend/requirements.txt >> requirements.txt
      fi
      
      echo "Final requirements.txt:"
      cat requirements.txt
    displayName: 'Create requirements.txt'

  # Step 2: Remove startup.sh and let Azure handle the startup
  - script: |
      echo "Cleaning up any existing startup scripts..."
      # Remove any existing startup scripts to let Azure handle it
      rm -f startup.sh
    displayName: 'Cleanup startup scripts'

  # Step 3: Deploy SOURCE CODE (not zip) - Let Azure build it
  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      package: '$(System.DefaultWorkingDirectory)'