trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'novya-serviceconnection'
  appName: 'backend-n'
  pythonVersion: '3.11'

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Set up Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  # Step 2: Install Django backend dependencies (root)
  - script: |
      echo "Installing Django backend dependencies..."
      pip install -r requirements.txt
    displayName: 'Install Django requirements'

  # Step 3: Install FastAPI backend dependencies (ai_backend)
  - script: |
      echo "Installing FastAPI backend dependencies..."
      cd ai_backend
      pip install -r requirements.txt
    displayName: 'Install FastAPI requirements'

  # Step 4: Verify uvicorn installation
  - script: |
      echo "Verifying uvicorn installation..."
      python -c "import uvicorn; print('✅ uvicorn installed successfully')"
    displayName: 'Verify FastAPI installation'

  # Step 5: Archive everything
  - task: ArchiveFiles@2
    displayName: 'Archive files for deployment'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
      replaceExistingArchive: true

  # Step 6: Deploy to Azure Web App
  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      package: '$(Build.ArtifactStagingDirectory)/backend.zip'
