trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'novya-serviceconnection'
  appName: 'backend-n'

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Create requirements.txt with ALL dependencies including openai
  - script: |
      echo "Creating comprehensive requirements.txt..."
      
      cat > requirements.txt << 'EOF'
      fastapi==0.104.1
      uvicorn[standard]==0.24.0
      python-multipart==0.0.6
      anyio==4.2.0
      typing-extensions==4.8.0
      pydantic==2.5.0
      python-dotenv==1.0.0
      openai==1.3.0
      tiktoken==0.5.2
      requests==2.31.0
      httpx==0.25.2
      EOF
      
      # Add any other requirements from ai_backend
      if [ -f "ai_backend/requirements.txt" ]; then
        echo "" >> requirements.txt
        grep -v -E "^(fastapi|uvicorn|python-multipart|anyio|typing-extensions|pydantic|python-dotenv|openai|tiktoken|requests|httpx)" ai_backend/requirements.txt >> requirements.txt
      fi
      
      echo "Final requirements.txt:"
      cat requirements.txt
    displayName: 'Create requirements.txt'

  # Step 2: Create startup command file to force FastAPI
  - script: |
      echo "Creating startup configuration..."
      
      # Create startup command file
      echo "cd ai_backend && python -m uvicorn app:app --host 0.0.0.0 --port 8000" > startup.txt
      
      # Create .env file
      cat > .env << 'EOF'
      WEBSITES_PORT=8000
      SCM_DO_BUILD_DURING_DEPLOYMENT=true
      EOF
    displayName: 'Create startup config'

  # Step 3: Deploy source code
  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      package: '$(System.DefaultWorkingDirectory)'