# azure-pipelines-single-command.yml
trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'novya-serviceconnection'
  appName: 'backend-n'
  pythonVersion: '3.11'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  - script: |
      echo "Installing dependencies..."
      pip install -r ai_backend/requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo "Testing application..."
      cd ai_backend
      python -c "from app import app; print('✅ App imports successfully')"
    displayName: 'Test app import'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
      replaceExistingArchive: true

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      package: '$(Build.ArtifactStagingDirectory)/backend.zip'

  # SINGLE COMMAND - No script file needed
  - task: AzureAppServiceManage@0
    displayName: 'Set Startup Command'
    inputs:
      azureSubscription: $(azureSubscription)
      Action: 'Start Azure App Service'
      WebAppName: $(appName)
      StartupCommand: 'cd /home/site/wwwroot && pip install --no-cache-dir -r ai_backend/requirements.txt && cd ai_backend && uvicorn app:app --host 0.0.0.0 --port 8000 --workers 2'