trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'novya-serviceconnection'
  appName: 'backend-n'
  pythonVersion: '3.11'

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Set up Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  # Step 2: Install Django backend dependencies (root)
  - script: |
      echo "Installing Django backend dependencies..."
      pip install -r requirements.txt
    displayName: 'Install Django requirements'

  # Step 3: Install FastAPI backend dependencies (ai_backend)
  - script: |
      echo "Installing FastAPI backend dependencies..."
      cd ai_backend
      pip install -r requirements.txt
    displayName: 'Install FastAPI requirements'

  # Step 4: Verify installations
  - script: |
      echo "Verifying installations..."
      python -c "import uvicorn; print('✅ uvicorn installed successfully')"
      cd ai_backend
      python -c "from main import app; print('✅ FastAPI app imported successfully')"
    displayName: 'Verify installations'

  # Step 5: Create proper startup script
  - script: |
      echo "Creating startup script..."
      cat > startup.sh << 'EOF'
      #!/bin/bash
      echo "Starting FastAPI application..."
      cd ai_backend
      uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --workers 4
      EOF
      chmod +x startup.sh
    displayName: 'Create startup script'

  # Step 6: Archive everything
  - task: ArchiveFiles@2
    displayName: 'Archive files for deployment'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
      replaceExistingArchive: true

  # Step 7: Deploy to Azure Web App
  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      package: '$(Build.ArtifactStagingDirectory)/backend.zip'