trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'novya-serviceconnection'
  appName: 'backend-n'
  pythonVersion: '3.11'

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Set up Python 3.11
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  # Step 2: Create requirements.txt with COMPATIBLE versions
  - script: |
      echo "Creating requirements.txt with compatible versions..."
      
      cat > requirements.txt << 'EOF'
      fastapi==0.104.1
      uvicorn[standard]==0.24.0
      python-multipart==0.0.6
      anyio==3.7.1
      typing-extensions==4.8.0
      pydantic==2.5.0
      python-dotenv==1.0.0
      openai==1.3.0
      tiktoken==0.5.2
      requests==2.31.0
      httpx==0.25.2
      EOF
      
      echo "Requirements.txt created with compatible versions"
      cat requirements.txt
    displayName: 'Create requirements.txt'

  # Step 3: Install dependencies
  - script: |
      echo "Installing dependencies..."
      pip install --upgrade pip
      pip install -r requirements.txt
      
      # Verify installations
      python -c "import uvicorn, fastapi, openai; print('✅ All dependencies installed successfully')"
    displayName: 'Install dependencies'

  # Step 4: Deploy SOURCE CODE to let Azure build
  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      package: '$(System.DefaultWorkingDirectory)'