# azure-pipelines-final.yml
trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'novya-serviceconnection'
  appName: 'backend-n'
  pythonVersion: '3.11'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  # Copy correct requirements.txt to root
  - script: |
      echo "Setting up requirements.txt..."
      echo "fastapi==0.104.1" > requirements.txt
      echo "uvicorn[standard]==0.27.0" >> requirements.txt
      echo "python-dotenv==1.0.0" >> requirements.txt
      echo "openai==1.3.0" >> requirements.txt
      echo "pydantic==2.5.0" >> requirements.txt
      echo "Requirements.txt created:"
      cat requirements.txt
    displayName: 'Create requirements.txt'

  - script: |
      echo "Installing dependencies..."
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo "Testing application..."
      cd ai_backend
      python -c "from app import app; print('✅ App imports successfully')"
    displayName: 'Test app import'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
      replaceExistingArchive: true

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      package: '$(Build.ArtifactStagingDirectory)/backend.zip'

  # Correct startup command
  - task: AzureAppServiceManage@0
    displayName: 'Set Startup Command'
    inputs:
      azureSubscription: $(azureSubscription)
      Action: 'Start Azure App Service'
      WebAppName: $(appName)
      StartupCommand: 'cd /home/site/wwwroot && pip install --no-cache-dir -r requirements.txt && cd ai_backend && python -m uvicorn app:app --host 0.0.0.0 --port 8000'