# Generated by Django 4.2.7 on 2025-10-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
    ]
