# Generated by Django 4.2.7 on 2025-10-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_auto_20251015_0930'),
    ]

    operations = [
    ]
