# Generated by Django 4.2.7 on 2025-10-12 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20250912_1250'),
    ]

    operations = [
        # Add new fields to QuizAttempt model
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_type',
            field=models.CharField(choices=[('database', 'Database Quiz'), ('ai_generated', 'AI Generated Quiz'), ('mock_test', 'Mock Test')], default='ai_generated', max_length=20),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='chapter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='subtopic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='difficulty_level',
            field=models.CharField(choices=[('simple', 'Simple'), ('medium', 'Medium'), ('hard', 'Hard')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='unanswered_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='completion_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='language',
            field=models.CharField(default='English', max_length=10),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_data_json',
            field=models.TextField(blank=True, null=True),
        ),
        # Update the foreign key to allow null values for AI-generated quizzes
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        # Update the foreign key to point to StudentRegistration
        migrations.AlterField(
            model_name='quizattempt',
            name='student_id',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='authentication.studentregistration'),
        ),
    ]
