name: Sync to Azure Repos

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git and Push to Azure
        env:
          AZURE_REPO_URL: ${{ secrets.AZURE_REPO_URL }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
        run: |
          # Configure git with correct email from your Azure DevOps account
          git config --global user.name "monika morla"
          git config --global user.email "monikanoria@Datastaggmail.onmicrosoft.com"

          # Clean the Azure Repos URL
          CLEAN_URL=$(echo "$AZURE_REPO_URL" | sed 's/[\r\n]//g' | xargs)
          
          # Construct authenticated URL
          if [[ $CLEAN_URL =~ https://dev.azure.com/([^/]+)/([^/]+)/_git/([^/]+) ]]; then
            ORG="${BASH_REMATCH[1]}"
            PROJECT="${BASH_REMATCH[2]}"
            REPO="${BASH_REMATCH[3]}"
            
            AUTH_URL="https://$AZURE_PAT@dev.azure.com/$ORG/$PROJECT/_git/$REPO"
            
            echo "Pushing to Azure DevOps organization: $ORG"
            echo "Project: $PROJECT"
            echo "Repository: $REPO"
            
            git remote add azure $AUTH_URL
            git push azure master:master --force
          else
            echo "Error: Invalid Azure Repos URL format"
            exit 1
          fi
