name: Sync to Azure Repos

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git and Push to Azure
        env:
          AZURE_REPO_URL: ${{ secrets.AZURE_REPO_URL }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
        run: |
          # Configure git
          git config --global user.name "monika morla"
          git config --global user.email "monikamoria@Datastaggmail.onmicrosoft.com"

          # Remove any incorrect username prefix and clean the URL
          CLEAN_URL=$(echo "$AZURE_REPO_URL" | sed 's|https://[^@]*@||' | sed 's/[\r\n]//g' | xargs)
          
          echo "Cleaned URL: $CLEAN_URL"
          
          # Validate URL format
          if [[ $CLEAN_URL =~ https://dev.azure.com/([^/]+)/([^/]+)/_git/([^/]+) ]]; then
            ORG="${BASH_REMATCH[1]}"
            PROJECT="${BASH_REMATCH[2]}"
            REPO="${BASH_REMATCH[3]}"
            
            echo "Organization: $ORG"
            echo "Project: $PROJECT"
            echo "Repository: $REPO"
            
            # Construct authenticated URL
            AUTH_URL="https://$AZURE_PAT@dev.azure.com/$ORG/$PROJECT/_git/$REPO"
            
            echo "Using authenticated URL (PAT hidden for security)"
            
            # Add remote and push
            git remote add azure $AUTH_URL
            git push azure master:master --force
            
            echo "Successfully pushed to Azure Repos!"
          else
            echo "Error: Invalid Azure Repos URL format"
            echo "Expected: https://dev.azure.com/{organization}/{project}/_git/{repository}"
            echo "Got: $CLEAN_URL"
            echo "Please check your AZURE_REPO_URL secret"
            exit 1
          fi
