name: Sync to Azure Repos

on:
  push:
    branches:
      - main  # Trigger when code is pushed to main in GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Azure Repos
        env:
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
        run: |
          # Configure Git
          git config --global user.name "monika morla"
          git config --global user.email "monikamoria@Datastaggmail.onmicrosoft.com"

          # Remove existing remote if it exists
          git remote remove azure 2>/dev/null || true

          # Construct the authenticated URL
          AZURE_REPO_URL="https://$AZURE_PAT@dev.azure.com/novya/Novya/_git/backend-n"
          
          echo "Setting up Azure remote..."
          git remote add azure "$AZURE_REPO_URL"
          
          echo "Pushing to Azure Repos main branch..."
          # Push from local main to Azure's main branch
          git push azure master:main --force
          
          echo "✅ Successfully synchronized with Azure Repos!"
