name: Sync to Azure Repos

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git and Push to Azure
        env:
          AZURE_REPO_URL: ${{ secrets.AZURE_REPO_URL }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
        run: |
          # Configure git
          git config --global user.name "monika morla"
          git config --global user.email "monikamoria@Datastaggmail.onmicrosoft.com"

          # Debug: Show original URL (masked)
          echo "Original URL: ${AZURE_REPO_URL:0:20}..."
          
          # Force clean URL - hardcode the correct format
          ORG="novya"
          PROJECT="Novya"
          REPO="backend-n"
          
          echo "Using hardcoded values:"
          echo "Organization: $ORG"
          echo "Project: $PROJECT"
          echo "Repository: $REPO"
          
          # Construct URLs
          CLEAN_URL="https://dev.azure.com/$ORG/$PROJECT/_git/$REPO"
          AUTH_URL="https://$AZURE_PAT@dev.azure.com/$ORG/$PROJECT/_git/$REPO"
          
          echo "Clean URL: $CLEAN_URL"
          echo "Auth URL: https://***@dev.azure.com/$ORG/$PROJECT/_git/$REPO"
          
          # Test network connectivity
          echo "Testing connectivity to Azure DevOps..."
          curl -I https://dev.azure.com --connect-timeout 10
          
          # Add remote and push
          git remote add azure "$AUTH_URL"
          git push azure master:master --force
