name: Sync to Azure Repos

on:
  push:
    branches:
      - master  # GitHub branch to trigger sync

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Push to Azure Repos using PAT
      - name: Push code to Azure Repos
        env:
          AZURE_REPO_URL: ${{ secrets.AZURE_REPO_URL }}  # Exact HTTPS clone URL from Azure DevOps
          AZURE_PAT: ${{ secrets.AZURE_PAT }}            # Personal Access Token with Code: Read & Write
        run: |
          # Configure Git identity
          git config --global user.name "monikamorla"
          git config --global user.email "monikamorla@Datastaggmail.onmicrosoft.com"

          # Remove any hidden newlines or spaces
          CLEAN_URL=$(echo "$AZURE_REPO_URL" | tr -d '\n' | tr -d '\r' | xargs)

          # Add remote without credentials first
          git remote add azure "$CLEAN_URL"

          # Update remote to include PAT for non-interactive authentication
          AUTH_URL="https://:$AZURE_PAT@$(echo "$CLEAN_URL" | sed -E 's#https://##')"
          git remote set-url azure "$AUTH_URL"

          # Test connectivity
          git ls-remote azure

          # Push code to Azure DevOps
          git push azure master --force
