name: Sync to Azure Repos

on:
  push:
    branches:
      - master  # Trigger on pushes to master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Push to Azure Repos using PAT
      - name: Push code to Azure Repos
        env:
          AZURE_PAT: ${{ secrets.AZURE_PAT }}  # Personal Access Token
        run: |
          # Configure Git identity
          git config --global user.name "monikamorla"
          git config --global user.email "monikamorla@Datastaggmail.onmicrosoft.com"

          # Add Azure remote with PAT for authentication
          git remote add azure https://:$AZURE_PAT@dev.azure.com/novya/Novya/_git/backend-n

          # Test connectivity
          git ls-remote azure

          # Push code
          git push azure master --force
